platform :ios, '8.0'

target 'xc_app_rn' do
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
    pod 'VerifyCode'
  pod 'react-native-video', :path => '../node_modules/react-native-video'

end
